#!/usr/bin/env python3
"""Compose Pasture demo art from Kenney 2D assets and emit demo/pasture-art-bytes.ts."""

from __future__ import annotations

import base64
import math
import os
from io import BytesIO

from PIL import Image, ImageDraw, ImageEnhance

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART_DIR = os.path.join(ROOT, "demo", "pasture-art")
SRC_FOLIAGE = os.path.join(ROOT, "assets", "kenney_foliage-sprites", "PNG", "Shaded")
SRC_COW = os.path.join(ROOT, "assets", "kenney_cube-pets_1.0", "Previews", "animal-cow.png")
OUT_TS = os.path.join(ROOT, "demo", "pasture-art-bytes.ts")

W, H = 1280, 720

ASSET_FILES = [
    "pasture-morning.jpg",
    "pasture-afternoon.jpg",
    "pasture-sunset.jpg",
    "pasture-night.jpg",
    "cow-idle.png",
    "cow-graze.png",
    "cow-walk.png",
    "cow-drink.png",
    "star.png",
]


def load_sprite(name: str) -> Image.Image:
    return Image.open(os.path.join(SRC_FOLIAGE, name)).convert("RGBA")


def sky(w: int, h: int, top: tuple[int, int, int], bottom: tuple[int, int, int]) -> Image.Image:
    img = Image.new("RGB", (w, h), top)
    px = img.load()
    for y in range(h):
        t = y / max(h - 1, 1)
        r = int(top[0] * (1 - t) + bottom[0] * t)
        g = int(top[1] * (1 - t) + bottom[1] * t)
        b = int(top[2] * (1 - t) + bottom[2] * t)
        for x in range(w):
            px[x, y] = (r, g, b)
    return img.convert("RGBA")


def paste_sprite(canvas: Image.Image, sprite: Image.Image, x: float, y: float, scale: float = 1.0, opacity: float = 1.0) -> None:
    s = sprite
    if scale != 1.0:
        s = s.resize((int(s.width * scale), int(s.height * scale)), Image.NEAREST)
    if opacity < 1.0:
        s = s.copy()
        alpha = s.split()[3].point(lambda a: int(a * opacity))
        s.putalpha(alpha)
    canvas.alpha_composite(s, (int(x - s.width / 2), int(y - s.height / 2)))


def build_background(
    filename: str,
    sky_top: tuple[int, int, int],
    sky_bottom: tuple[int, int, int],
    overlay: tuple[int, int, int, int] | None = None,
    vignette: float = 0.0,
) -> None:
    canvas = sky(W, H, sky_top, sky_bottom)
    for spr, x, y, sc, op in [
        ("sprite_0066.png", W * 0.22, H * 0.72, 0.95, 0.85),
        ("sprite_0058.png", W * 0.78, H * 0.74, 0.9, 0.85),
        ("sprite_0060.png", W * 0.5, H * 0.78, 1.05, 0.75),
        ("sprite_0055.png", W * 0.12, H * 0.82, 0.85, 0.9),
        ("sprite_0056.png", W * 0.88, H * 0.83, 0.85, 0.9),
    ]:
        paste_sprite(canvas, load_sprite(spr), x, y, sc, op)

    grass = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    for spr, x, y, sc, op in [
        ("sprite_0058.png", W * 0.18, H * 0.92, 1.15, 1.0),
        ("sprite_0052.png", W * 0.42, H * 0.94, 1.2, 1.0),
        ("sprite_0057.png", W * 0.68, H * 0.93, 1.15, 1.0),
        ("sprite_0059.png", W * 0.9, H * 0.92, 1.1, 0.95),
    ]:
        paste_sprite(grass, load_sprite(spr), x, y, sc, op)
    grass = ImageEnhance.Color(grass).enhance(1.15)
    canvas = Image.alpha_composite(canvas, grass)

    if overlay:
        canvas = Image.alpha_composite(canvas, Image.new("RGBA", (W, H), overlay))
    if vignette > 0:
        v = Image.new("RGBA", (W, H), (0, 0, 0, 0))
        d = ImageDraw.Draw(v)
        d.ellipse([-W * 0.1, -H * 0.05, W * 1.1, H * 1.05], fill=(0, 0, 0, int(255 * vignette)))
        canvas = Image.alpha_composite(canvas, v)

    canvas.convert("RGB").save(os.path.join(ART_DIR, filename), "JPEG", quality=88, optimize=True)


def build_cow_sprite(filename: str, flip: bool = False, size: int = 256) -> None:
    im = Image.open(SRC_COW).convert("RGBA")
    if flip:
        im = im.transpose(Image.FLIP_LEFT_RIGHT)
    im.resize((size, size), Image.NEAREST).save(os.path.join(ART_DIR, filename), "PNG")


def build_star() -> None:
    star = Image.new("RGBA", (128, 128), (0, 0, 0, 0))
    d = ImageDraw.Draw(star)
    cx, cy, r = 64, 64, 28
    points = []
    for i in range(10):
        ang = math.pi / 2 + i * math.pi / 5
        rad = r if i % 2 == 0 else r * 0.4
        points.append((cx + rad * math.cos(ang), cy - rad * math.sin(ang)))
    d.polygon(points, fill=(255, 245, 180, 240))
    d.ellipse([cx - 8, cy - 8, cx + 8, cy + 8], fill=(255, 255, 220, 255))
    star.save(os.path.join(ART_DIR, "star.png"), "PNG")


def emit_typescript_bytes() -> None:
    lines = [
        "/** Auto-generated by scripts/build-pasture-art.py — do not edit by hand. */",
        "",
        "function decodeBase64(base64: string): Uint8Array {",
        "  if (typeof globalThis.atob === 'function') {",
        "    const binary = globalThis.atob(base64);",
        "    const bytes = new Uint8Array(binary.length);",
        "    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);",
        "    return bytes;",
        "  }",
        "  throw new Error('Base64 decoding is unavailable in this runtime.');",
        "}",
        "",
        "const PASTURE_ART_BASE64: Record<string, string> = {",
    ]

    for name in ASSET_FILES:
        path = os.path.join(ART_DIR, name)
        with open(path, "rb") as f:
            encoded = base64.b64encode(f.read()).decode("ascii")
        lines.append(f"  '{name}': '{encoded}',")

    lines.extend([
        "};",
        "",
        "export const PASTURE_ART_BYTES: Readonly<Record<string, Uint8Array>> = Object.fromEntries(",
        "  Object.entries(PASTURE_ART_BASE64).map(([name, data]) => [name, decodeBase64(data)]),",
        ");",
        "",
        "export function getPastureArtBytes(name: string): Uint8Array | undefined {",
        "  return PASTURE_ART_BYTES[name];",
        "}",
        "",
        "export const PASTURE_ART_SIZES: Readonly<Record<string, number>> = Object.fromEntries(",
        "  Object.entries(PASTURE_ART_BYTES).map(([name, bytes]) => [name, bytes.length]),",
        ");",
        "",
    ])

    with open(OUT_TS, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> None:
    os.makedirs(ART_DIR, exist_ok=True)
    build_background("pasture-morning.jpg", (135, 206, 250), (180, 220, 170), (255, 240, 200, 35))
    build_background("pasture-afternoon.jpg", (100, 180, 255), (120, 190, 100), (255, 255, 220, 20))
    build_background("pasture-sunset.jpg", (255, 140, 60), (80, 50, 90), (255, 120, 40, 55), vignette=0.12)
    build_background("pasture-night.jpg", (15, 20, 45), (10, 25, 35), (20, 30, 80, 90), vignette=0.25)

    build_cow_sprite("cow-idle.png")
    build_cow_sprite("cow-graze.png", size=240)
    build_cow_sprite("cow-walk.png", flip=True)
    build_cow_sprite("cow-drink.png", flip=True, size=240)
    build_star()
    emit_typescript_bytes()
    print(f"Wrote {len(ASSET_FILES)} art files and {OUT_TS}")


if __name__ == "__main__":
    main()
